version: "3.8"
services:
  frontend:
    container_name: portfolio-dev
    image: portfolio-dev:1.0
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
