version: "3.8"
services:
  frontend:
    container_name: portfolio-prod
    image: portfolio-prod:1.0
    build:
      context: .
      target: production
    ports:
      - 80:80
      - 443:443
    environment:
      - NODE_ENV=production
